<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <WindowsAppSdkBootstrapInitialize>true</WindowsAppSdkBootstrapInitialize>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StaminaManager.Core\StaminaManager.Core.csproj" />
    <ProjectReference
      Include="..\StaminaManager\StaminaManager.csproj"
      SetConfiguration="Configuration=UnitTest;WindowsAppSdkDeploymentManagerInitialize=false;PublishReadyToRun=false;PublishTrimmed=false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
